### ISSUE TITLE
all pods and containers should implement resource requests and limits

### ISSUE THREAD

**Issue by simonsdave** [simonsdave/cloudfeaster-services#54]
references

- [Managing Compute Resources for Containers](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#how-pods-with-resource-requests-are-scheduled)
- [Resource Quality of Service in Kubernetes](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/resource-qos.md)
- [How to estimate CPU requirements for a Kubernetes pod?](https://stackoverflow.com/questions/43922056/how-to-estimate-cpu-requirements-for-a-kubernetes-pod)

process to get this started

- spin up a cluster using 3 x n1-standard-1 nodes
- helm deploy a 3 pod memcached cluster
- create the discovery deployment and configure it to run every 30 seconds
- create the spiders deployment with various resource constraints and run a simple load test to get a sense of performance under the various resource constraints 
- load test is ```ab -k -c 10 -n 100000 http://23.251.158.227/v1.0/spiders```
- also monitoring the deployment using [Stackdriver Monitoring](https://cloud.google.com/kubernetes-engine/docs/how-to/monitoring) and the [Google Cloud Console](https://console.cloud.google.com/kubernetes)

**Comment by simonsdave** [comment]
Resource constraints.

```
None:-)
```

Results of running load test

```
Percentage of the requests served within a certain time (ms)
  50%     46
  66%     48
  75%     52
  80%     57
  90%     73
  95%     81
  98%     88
  99%     92
 100%    815 (longest request)
```

**Comment by simonsdave** [comment]
Resource constraints.

```
containers:
- name: service
  image: gcr.io/cloudfeaster/services:latest
  command: [ "spiders.py", "--config", "/clf/config.ini" ]
  resources:
    requests:
      memory: "25M"
      cpu: "50m"
    limits:
      memory: "50M"
      cpu: "100m"
  ports:
  - containerPort: 8081
  volumeMounts:
  - name: service-config
    mountPath: /clf
- name: kubectl-sidecar
  image: gcr.io/cloudfeaster/kubectl:latest
  imagePullPolicy: Always
  command: [ "kubectl", "proxy", "--address", "127.0.0.1", "--port", "8080"]
  resources:
    requests:
      memory: "15M"
      cpu: "25m"
    limits:
      memory: "20M"
      cpu: "50m"
- name: mcrouter-sidecar
  image: gcr.io/cloudfeaster/jamescarr_mcrouter:1.0
  imagePullPolicy: Always
  command: [ "mcrouter", "-p", "11211", "-f", "/clf/mcrouter.jsonish"]
  resources:
    requests:
      memory: "15M"
      cpu: "25m"
    limits:
      memory: "20M"
      cpu: "50m"
```

Results of running load test

```
Percentage of the requests served within a certain time (ms)
  50%    100
  66%    104
  75%    110
  80%    157
  90%    196
  95%    200
  98%    206
  99%    225
 100%   1147 (longest request)
```

**Comment by simonsdave** [comment]
Resource constraints.

```
- name: service
  image: gcr.io/cloudfeaster/services:latest
  command: [ "spiders.py", "--config", "/clf/config.ini" ]
  resources:
    requests:
      memory: "25M"
      cpu: "100m"
    limits:
      memory: "50M"
      cpu: "200m"
  ports:
  - containerPort: 8081
  volumeMounts:
  - name: service-config
    mountPath: /clf
- name: kubectl-sidecar
  image: gcr.io/cloudfeaster/kubectl:latest
  imagePullPolicy: Always
  command: [ "kubectl", "proxy", "--address", "127.0.0.1", "--port", "8080"]
  resources:
    requests:
      memory: "15M"
      cpu: "25m"
    limits:
      memory: "20M"
      cpu: "50m"
- name: mcrouter-sidecar
  image: gcr.io/cloudfeaster/jamescarr_mcrouter:1.0
  imagePullPolicy: Always
  command: [ "mcrouter", "-p", "11211", "-f", "/clf/mcrouter.jsonish"]
  resources:
    requests:
      memory: "15M"
      cpu: "25m"
    limits:
      memory: "20M"
      cpu: "50m"
```

Results of running load test

```
Percentage of the requests served within a certain time (ms)
  50%     56
  66%     75
  75%     87
  80%     92
  90%    101
  95%    110
  98%    140
  99%    180
 100%   1887 (longest request)
```

**Comment by simonsdave** [comment]
Resource constraints.

```
containers:
  - name: service
    image: gcr.io/cloudfeaster/services:latest
    command: [ "spiders.py", "--config", "/clf/config.ini" ]
    resources:
      requests:
        memory: "25M"
        cpu: "200m"
      limits:
        memory: "50M"
        cpu: "300m"
    ports:
    - containerPort: 8081
    volumeMounts:
    - name: service-config
      mountPath: /clf
  - name: kubectl-sidecar
    image: gcr.io/cloudfeaster/kubectl:latest
    imagePullPolicy: Always
    command: [ "kubectl", "proxy", "--address", "127.0.0.1", "--port", "8080"]
    resources:
      requests:
        memory: "15M"
        cpu: "25m"
      limits:
        memory: "20M"
        cpu: "50m"
  - name: mcrouter-sidecar
    image: gcr.io/cloudfeaster/jamescarr_mcrouter:1.0
    imagePullPolicy: Always
    command: [ "mcrouter", "-p", "11211", "-f", "/clf/mcrouter.jsonish"]
    resources:
      requests:
        memory: "15M"
        cpu: "25m"
      limits:
        memory: "20M"
        cpu: "50m"
```

Results of running load test

```
Percentage of the requests served within a certain time (ms)
  50%     48
  66%     51
  75%     54
  80%     58
  90%     75
  95%     84
  98%     92
  99%    111
 100%   1315 (longest request)
```
